// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-n7zqEQ8dUClL5S0Um5o649t9tSXeklo',
    appId: '1:259077268985:web:26e8eb4b7c1f4251468928',
    messagingSenderId: '259077268985',
    projectId: 'food-app-flutter-97257',
    authDomain: 'food-app-flutter-97257.firebaseapp.com',
    storageBucket: 'food-app-flutter-97257.appspot.com',
    measurementId: 'G-T61LBQ7H5N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwOQ-Z1_w-LGirXSXTPBOJCY7ScggHizg',
    appId: '1:259077268985:android:a1a583eef69e647e468928',
    messagingSenderId: '259077268985',
    projectId: 'food-app-flutter-97257',
    storageBucket: 'food-app-flutter-97257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCru6bMWDMPrPfbENzvLJXnMTvN_Aswc8A',
    appId: '1:259077268985:ios:865eee01b7b714c3468928',
    messagingSenderId: '259077268985',
    projectId: 'food-app-flutter-97257',
    storageBucket: 'food-app-flutter-97257.appspot.com',
    iosClientId: '259077268985-bf7d495oul3t5sav9o31h8rgriaicp7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCru6bMWDMPrPfbENzvLJXnMTvN_Aswc8A',
    appId: '1:259077268985:ios:865eee01b7b714c3468928',
    messagingSenderId: '259077268985',
    projectId: 'food-app-flutter-97257',
    storageBucket: 'food-app-flutter-97257.appspot.com',
    iosClientId: '259077268985-bf7d495oul3t5sav9o31h8rgriaicp7l.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
